#!/usr/bin/env zsh

# starts the jack audio server daemon for macos

# check the following:
# jackd --help
# jackd -d coreaudio --help

LEADER_BACKEND=coreaudio
FOLLOWER_BACKEND=coremidi

JN_SCRIPT="$(dirname $0)/scripts/jackname.pl"
# use script to detect audio interface internal name (unstable across connections)
AUDIO_INTERFACE=$($JN_SCRIPT ES-9)

echo
cat "$(dirname $0)/banner"
echo
grep 'version\s*=\s*[.\d_-]*' build.gradle
echo audio interface: "$AUDIO_INTERFACE"
echo follower backend: "$FOLLOWER_BACKEND"
echo
echo starting jackd
echo

set -vx
jackd -v -X "$FOLLOWER_BACKEND" -d "$LEADER_BACKEND" -d "$AUDIO_INTERFACE" -P "$AUDIO_INTERFACE" -C "$AUDIO_INTERFACE" -i 16 -o 16 -r 96000

